### ISSUE TITLE
实体类中定义的Mapper接口可以查询到数据,重新定义的Mapper接口查询报错

### ISSUE THREAD

**Issue by 86jkuncle** [actframework/act-beetlsql#15]
开发环境:IDEA 2018.3
JDK版本:1.8,
POM文件部份内容:

```xml
<parent>
    <groupId>org.actframework</groupId>
    <artifactId>act-starter-parent</artifactId>
    <version>1.8.28.0</version>
  </parent>

<dependency>
      <groupId>org.actframework</groupId>
      <artifactId>act-beetlsql</artifactId>
      <version>1.7.1</version>
    </dependency>

    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
      <version>3.4.1</version>
    </dependency>

    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>5.1.48</version>
    </dependency>
```

DemoController.java (控制器)

```java
package com.example.controller
@UrlContext("/demo")
@With(BeetlSqlTransactional.class)
public class DemoController {
    //这里注入了实体类中的Mapper,没有问题
   // 这里把 Demo.Mapper 替换成 DemoMapper 就有问题,查询报错,DemoMapper定义在下面
    @Inject
    private  **Demo.Mapper** mapper;

    @GetAction("list")
    public List<Demo> list(){
        return mapper.all();
    }
}
```

Demo.java (实体)

```java
package com.example.entity
@Entity
public class Demo implements SimpleBean {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    public Integer id;

    @Column
    public String gender;

    @Column
    public String email;
    //这里在实体类中定义了Mapper接口
    public interface Mapper extends BaseMapper<Demo>{

    }
}
```

DemoMapper.java (重新定义的DemoMapper)

```java
package com.example.mapper
public interface DemoMapper extends BaseMapper<Demo> {
}
```

将DemoMapper注入到 Controller,查询报错,具体错误

```
HTTP/1.1 500 Server Error
调用请求处理器 com.example.api.DemoController.list 时发生错误: Server Error
 - org.osgl.inject.InjectException: Cannot instantiate interface com.example.mapper.DemoMapper(mapper)
```

出错的程序源码

```java
1 package com.example.api;
2 
3 import act.controller.Controller;
4 import act.controller.annotation.UrlContext;
5 import act.db.beetlsql.BeetlSqlTransactional;
6 import com.example.entity.Demo;
7 import com.example.mapper.DemoMapper;
8 import org.osgl.mvc.annotation.GetAction;
9 import org.osgl.mvc.annotation.With;
10 
11 import javax.inject.Inject;
12 import java.util.List;
13 
14 /**
15  * @author Administrator
16  * @date 2019/10/15 14:38
17  */
18 @UrlContext("/demo")
19 @With(BeetlSqlTransactional.class)
20 public class DemoController {
21     @Inject
22     private DemoMapper mapper;
23 
24     @GetAction("list")
25     public List<Demo> list(){
26         return mapper.all();
27     }
28 }
```

错误栈

```
at org.osgl.inject.Genie.findProvider(Genie.java:955)
at org.osgl.inject.Genie.fieldInjector(Genie.java:1092)
at org.osgl.inject.Genie.fieldInjectors(Genie.java:1082)
at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:1023)
at org.osgl.inject.Genie.buildProvider(Genie.java:1003)
at org.osgl.inject.Genie.findProvider(Genie.java:961)
at org.osgl.inject.Genie.getProvider(Genie.java:599)
at act.inject.genie.GenieInjector.getProvider(GenieInjector.java:81)
at act.inject.param.ParamValueLoaderService.findBeanLoader(ParamValueLoaderService.java:219)
at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:131)
at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:910)
at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:600)
at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:558)
at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
at act.app.ActionContext.proceedWithHandler(ActionContext.java:1366)
at act.route.Router$ContextualHandler.handle(Router.java:1771)
at act.xio.NetworkHandler$3.run(NetworkHandler.java:183)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
无法重现，参见项目：https://github.com/act-gallery/todo-beetlsql/tree/gh15

**Comment by 86jkuncle** [comment]
act-starter-parent 从 1.8.28.0 改成 1.8.28.1 就可以了
