### ISSUE TITLE
继承BeetlSqlDao基类，注入其他类中使用报错

### ISSUE THREAD

**Issue by donald2150** [actframework/act-beetlsql#20]
Source code:

```java
public class BaseDao<T, ID> extends BeetlSqlDao<ID, T>{

    public int insert(T entity) {
        return getSqlManager().insert(entity, true);
    }

    public int[] insert(List<T> entitys) {
        return getSqlManager().insertBatch(this.modelType(), entitys, true);
    }

    public int update(T entity) {
        return getSqlManager().updateById(entity);
    }

    public int[] update(List<T> entitys) {
        return getSqlManager().updateByIdBatch(entitys);
    }

}
```

```java
public class BaseServiceImpl<T, ID> implements BaseService<T, ID>{

    @Inject
    protected BaseDao<T, ID> baseDao;

    public T findById(ID id) throws EntityNotFoundException{
        T entity = (T) baseDao.findById(id);
        if (entity == null)
            throw new EntityNotFoundException("entity not found in database");
        return entity;
    }

    public T deleteById(ID id) throws EntityNotFoundException{
        T entity = this.findById(id);
        baseDao.delete(entity);
        return entity;
    }

    public T insert(T entity) {
        baseDao.insert(entity);
        return entity;
    }

    public T update(T entity) {
        baseDao.update(entity);
        return entity;
    }

    public T save(T entity) {
        baseDao.save(entity);
        return entity;
    }

    public List<T> insert(List<T> entitys) {
        baseDao.insert(entitys);
        return entitys;
    }

    public List<T> update(List<T> entitys) {
        baseDao.update(entitys);
        return entitys;
    }

    public List<T> all() {
        return baseDao.findAllAsList();
    }

}
```

```java
public class DemoDao extends BaseDao<Demo, Long> implements IDemoDao<Long, Demo>{


}
```

Error stack:

```
java.lang.IllegalArgumentException: Cannot find type implementation for class com.wasu.webframe.base.BaseDao
	at org.osgl.util.E.illegalArgumentIf(E.java:727)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:304)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:65)
	at act.db.DaoBase.exploreTypes(DaoBase.java:125)
	at act.db.DaoBase.<init>(DaoBase.java:50)
	at act.db.beetlsql.BeetlSqlDao.<init>(BeetlSqlDao.java:43)
	at com.wasu.webframe.base.BaseDao.<init>(BaseDao.java:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.osgl.inject.Genie$11.get(Genie.java:1046)
	at org.osgl.inject.Genie$9.get(Genie.java:999)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:467)
	at org.osgl.inject.Genie$11.get(Genie.java:1052)
	at org.osgl.inject.Genie$9.get(Genie.java:999)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:467)
	at org.osgl.inject.Genie$11.get(Genie.java:1052)
	at org.osgl.inject.Genie$9.get(Genie.java:999)
	at act.inject.param.ParamValueLoaderService$2.load(ParamValueLoaderService.java:247)
	at act.inject.param.ParamValueLoaderService$6.load(ParamValueLoaderService.java:719)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:80)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:152)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:979)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:614)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:584)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1456)
	at act.route.Router$ContextualHandler.handle(Router.java:1815)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
@donald2150 I need the source code of the controller or the class that you inject `BaseDao`
